# Generated by Django 3.2.8 on 2021-11-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
