# Generated by Django 3.2.9 on 2022-03-26 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_contact_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dt',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
